### ISSUE TITLE
Comments on README

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly-config#2]
At a high-level, this repo should be usable without knowledge of Sandmark. The sandmark nightly user will have a branch that they want to benchmark, perhaps know whether they want to run sequential or parallel benchmarks. But beyond that, there should be no assumption of the knowledge about sandmark. To that end, Sandmark nightly config does not need to expose every option that is available under Sandmark. As it stands, there are several improvements that could be made:

What is the relationship between `tag` and `config_json` parameters? Are these two [parameters related](https://github.com/ocaml-bench/sandmark/blob/main/README.md#tags). If you have a `tag`, then you will always have to use `_filtered.json`? Otherwise, the filtering would not take effect and you will run the unfiltered ones. Suggestion:

* Remove the `tag` option from the parameters, and always assume that the tag is `macro_bench`. 
* Remove the `config_json` option. The names are not illustrative and confusing. By default, always run the sequential and parallel benchmarks. For parallel benchmarks, choose the appropriate json file based on the machine.

Isn't the `runparams` redundant since you can always provide the information through the `environment` variable? Suggestion:

* Remove the `runparams` option.

**Comment by shakthimaan** [comment]
> What is the relationship between tag and config_json parameters? Are these two [parameters related](https://github.com/ocaml-bench/sandmark/blob/main/README.md#tags).

The `tag` is used in the `config_json` to select the benchmarks.

> Remove the tag option from the parameters, and always assume that the tag is macro_bench.

Okay.

> Remove the config_json option

Sure.

> Isn't the runparams redundant since you can always provide the information through the environment variable?

The `runparams` is used when building the `ocaml-base-compiler`, whereas, the `environment` is used when running the benchmarks.

**Comment by kayceesrk** [comment]
> The tag is used in the config_json to select the benchmarks.

You didn't answer my question + observation:

> If you have a tag, then you will always have to use _filtered.json? Otherwise, the filtering would not take effect and you will run the unfiltered ones.

If I did `tag=macro_bench` and `config_json=run_config.json`, will you not run **_all_** the benchmarks, and not just the macro benchmarks? Either way, the meaning is incorrect. If you run the macro benchmarks only then you have ignored the user request to run all the benchmarks in `run_config.json` (if the user wants to run only the macro benchmarks should they do `config_json=run_config_filtered.json`??). If you run all the benchmarks then you are ignoring `macro_bench` tag. Please confirm what the intended behaviour is.

Either way, remove the options.

**Comment by shakthimaan** [comment]
> If I did tag=macro_bench and config_json=run_config.json, will you not run all the benchmarks, 

Yes, we will not run all the benchmarks. 

> and not just the macro benchmarks?

Yes, just the macro benchmarks.

> If you run the macro benchmarks only then you have ignored the user request to run all the benchmarks in run_config.json

The `run_config.json` is a configuration file. The tag is used to filter the benchmarks from this configuration.

> Either way, remove the options.

Sure.

**Comment by kayceesrk** [comment]
> The run_config.json is a configuration file. The tag is used to filter the benchmarks from this configuration.

This is confusing because the examples in the README file all use `_filtered.json` in addition to `tag`: https://github.com/ocaml-bench/sandmark-nightly-config#example

Best to remove these options.

**Comment by shakthimaan** [comment]
> Best to remove these options.

Updated in commit https://github.com/ocaml-bench/sandmark-nightly-config/commit/471eee5c1eccef44090ea8224335b063bc8daea8 and https://github.com/ocaml-bench/sandmark-nightly-config/commit/612b0c4363cb087f6465d965b89b2ab7836ec4d5.

**Comment by kayceesrk** [comment]
Why is `config_json` and `tag` still used in https://github.com/ocaml-bench/sandmark-nightly-config/commit/471eee5c1eccef44090ea8224335b063bc8daea8. It has been made optional, but the observation I make in this thread is that they are semantically broken: https://github.com/ocaml-bench/sandmark-nightly-config/issues/2#issuecomment-1057777196. 

I am uncomfortable having these semantically broken options, even if they are optional. Currently, it is not clear what the user will get when they use the options. The fix is not to add more documentation but simplify by removing the option.

**Comment by shakthimaan** [comment]
> The fix is not to add more documentation but simplify by removing the option.

I have now listed the minimal options in the README with this commit https://github.com/ocaml-bench/sandmark-nightly-config/commit/a9bc9d42f1d8e6da9817e7b96891fb5fadfd16de.

**Comment by kayceesrk** [comment]
Thanks!
