### ISSUE TITLE
"configure" parameter not taken into account

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml-bench/sandmark-nightly-config#22]
The run results for the `5.2.0+trunk+tsan+sequential`, introduced in https://github.com/ocaml-bench/sandmark-nightly-config/pull/20, do not make sense: TSan instrumentation should incur a big slowdown. I suspect that the `"configure": "--enable-tsan"` parameter is ignored by Sandmark.

**Comment by punchagan** [comment]
@OlivierNicole your suspicion seems to be correct. Thanks for the report! I'll take a look into this and fix it.

**Comment by punchagan** [comment]
Closed in  ocaml-bench/sandmark#456

**Comment by OlivierNicole** [comment]
Thank you!

**Comment by punchagan** [comment]
Thank you for the report, @OlivierNicole. 

If the old results don't make sense, I wonder if it is better to remove those benchmark results from Sandmark, so that folks using the UI aren't confused.

**Comment by OlivierNicole** [comment]
I had set 31 May as expiry date. Not sure how long benchmark results are kept.

Also, I would be interested to configure Sandmark to run benchmarks with `--enable-tsan` again, but maybe when the TSan branch is merged or at least very stable. One point I am worried about is that enabling TSan requires `libunwind` being installed, which I am not sure is the case on the Sandmark machines.

**Comment by punchagan** [comment]
> I had set 31 May as expiry date. Not sure how long benchmark results are kept.

The expiry date is for the configuration and running the benchmarks, not the generated results. The results themselves are currently retained forever. We don't have a policy on deleting the old results, as of now, though @kayceesrk did mention cleaning up benchmark results that are older than an year. 

> One point I am worried about is that enabling TSan requires `libunwind` being installed, which I am not sure is the case on the Sandmark machines.

I'll verify that, and ensure the machines have `libunwind` installed. Thanks!

**Comment by OlivierNicole** [comment]
Thank you for your help with this :)
