### ISSUE TITLE
Trunk OCaml version

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly-config#4]
Trunk version is now `5.1.0`.

```bash
$ ocamlopt.opt --version
5.1.0+dev1-2022-06-09
```

Does this not cause an issue here?
https://github.com/ocaml-bench/sandmark-nightly-config/blob/595cdaeae18870bab454046d131b48aff6211b84/config/custom_turing.json#L4

**Comment by shakthimaan** [comment]
Yes, we need to bump the sandmark-nightly-config to use 5.1.0+trunk. We have Sandmark CI benchmarks running for 5.1.0+trunk, and we are still testing the build of the remaining benchmarks for the same.

**Comment by kayceesrk** [comment]
I added a new request to sandmark nightly config

https://github.com/ocaml-bench/sandmark-nightly-config/blob/main/config/custom_turing.json#L7-L10

Is this expected to fail then?

**Comment by shakthimaan** [comment]
> Is this expected to fail then?

Yes. The default dune version in the switch on these servers is `2.9.0`. We will need to update the servers to use `dune.2.9.3-5.0.0` from the -alpha repository since we use the USE_SYS_DUNE_HACK option to build the benchmarks. After the `macro_bench` benchmarks build fine in our testing, we will update the servers with the latest dune version for the nightly runs.

**Comment by kayceesrk** [comment]
Can you schedule this as a priority, please? Now that OCaml trunk default version is `5.1.0+..`, developers will produce PRs against this version. Currently, they can't use sandmark nightly config facility.

**Comment by shakthimaan** [comment]
Yes, we are taking this as high priority. We will update sandmark-nightly-config and the Sandmark setup on the servers to build for `5.1.0+trunk`.

**Comment by shakthimaan** [comment]
`sandmark-nightly-config` has been updated to use `5.1.0+trunk` with the latest dune.2.9.3-5.0.0 from the -alpha repository. The `5.1.0+trunk` and `5.1.0+trunk+decouple_major_and_minor2` results from Navajo and Turing servers are also available at https://sandmark.tarides.com.
